---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "thetarto/ansible-${MOLECULE_DISTRIB}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
provisioner:
  name: ansible
